#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

source $HOME/.config/bspwm/bspwmrc_local

bspc config border_width           2
bspc config window_gap             6
bspc config top_padding            27
bspc config focused_border_color   "#9b8419"
bspc config focus_follows_pointer  true

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config single_monocle       true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Load ~/.Xresources, sets dpi
xrdb -merge -I$HOME $HOME/.Xresources

# Polybar
source $HOME/.config/polybar/launch.sh &

#Picom - Compositor for Xorg
killall -q picom
picom -b --backend xr_glx_hybrid --vsync --vsync-use-glfinish &

# Dunst - Notification daemon
dunst &

# Set wallpaper
feh --bg-scale $HOME/.config/wallpaper/wallpaper.jpg &

# nm-applet - Network manager applet
nm-applet &

# Blueman - Bluetooth manager
blueman-applet &

# Synergy - Virtual KVM
synergyc 192.168.1.128 &

# Flameshot - GUI Screenshot utility
flameshot R
