#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall -q picom
picom -b --backend xr_glx_hybrid --vsync --vsync-use-glfinish &

bspc monitor HDMI-A-0 -d 1 3 5 7 9
bspc monitor DVI-D-0  -d 2 4 6 8 0

bspc config border_width         2
bspc config window_gap           4
bspc config top_padding	         32
bspc config focused_border_color   "#9b8419"
bspc config focus_follows_pointer  true

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config single_monocle

# Polybar
source $HOME/.config/polybar/launch.sh &

# Set wallpaper
feh --bg-scale $HOME/.config/wallpaper/orange.png &

# Dunst - Notification daemon
dunst &
