#!/usr/bin/env bash

# Run basic_install from current directory
. "$(dirname "$0")/basic_install"

# Conda installation

if ! __has conda; then
    case $(uname) in
        Linux)
            curl -fLo "${XDG_DATA_HOME}/miniconda3.sh" --create-dirs https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            ;;
        Darwin)
            case $(uname -m) in
                arm64)
                    curl -fLo "${XDG_DATA_HOME}/miniconda3.sh" --create-dirs https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
                    ;;
                *)
                    curl -fLo "${XDG_DATA_HOME}/miniconda3.sh" --create-dirs https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
                    ;;
            esac
            ;;
        *) echo "Not sure what system are you using, cannot install miniconda";;
    esac

    bash "${XDG_DATA_HOME}/miniconda3.sh" -b -p "${XDG_DATA_HOME}/miniconda3" -f
    rm "${XDG_DATA_HOME}/miniconda3.sh"
    eval "${XDG_DATA_HOME}/miniconda3/bin/python ${DOTFILES}/install/lib/init_zsh.py"
fi
